export const LIST_ALL = 'LIST_ALL';
export const SAVE_TASK = 'SAVE_TASK';
export const OPEN_FORM = 'OPEN_FORM';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const CLOSE_FORM = 'CLOSE_FORM';
export const CLEAR_FORM = 'CLEAR_FORM';
export const UPDATE_STATUS_TASK = 'UPDATE_STATUS_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const FILTER_TABLE = 'FILTER_TABLE';
export const SEARCH_TASK = 'SEARCH_TASK';
export const SORT_TASK = 'SORT_TASK';


export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};
export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',
};